### ISSUE TITLE
Support half word loading/storing in Pancake

### ISSUE THREAD

**Issue by JunmingZhao42** [CakeML/cakeml#1000]
Currently there're ways to load/store words and bytes, but not a direct way to load/store half words.
It'd be a good usability improvements to support those operations, with something like:
```
var half = ldh address;
sth address, half;

!ldh half, address;
!sth half, address;
```

**Comment by IlmariReissumies** [comment]
Do you anticipate needing 16bit read/writes on 64-bit archs? Or is this mainly to have 32-bit instructions on 64?

**Comment by JunmingZhao42** [comment]
> Do you anticipate needing 16bit read/writes on 32-bit archs? Or is this mainly to have 32-bit instructions on 64?

I am currently only working on 64-bit archs for now (probably for the next few months as well), so it's mainly to have  32-bit instructions on 64.

**Comment by JunmingZhao42** [comment]
Sorry I might just have to take my words back... :) I came across cases where 16-bit read/writes are also needed.

16-bit read/writes are not as necessarily needed as 32 bit reads/writes (which are needed because of the device registers that I am dealing with are of 32-bit length, and accessing multiple times with `!ld8` will change the device state), but would be quite handy to have them.

**Comment by JunmingZhao42** [comment]
> Do you anticipate needing 16bit read/writes on 32-bit archs? Or is this mainly to have 32-bit instructions on 64?

Sorry I might just have to take my words back... :) I came across cases where 16-bit read/writes are also needed.

16-bit read/writes are not as necessarily needed as 32 bit reads/writes (which are needed because of the device registers that I am dealing with are of 32-bit length, and accessing multiple times with !ld8 will change the device state), but would be quite handy to have them.

**Comment by gernotheiser** [comment]
I would be surprised if there were no devices requiring 16-bit accesses.
Device word size is basically independent of processor word size

**Comment by IlmariReissumies** [comment]
@mktnk3 and I poked around in the L3 models a bit to see whether they have the necessary instructions to target:

- x64 has 16-bit and 32-bit versions of loads and stores
- MIPS has 32-bit loads and stores, but not 16-bit ones
- 32-bit ARMv7 has a `LoadHalf` which I assume is 16-bit
- 64-bit ARMv8 has 16-bit and 32-bit loads and stores
- RISC-V has 32-bit and 16-bit loads and stores (LWU vs LHU)
- ag32 is 32-bit, but has no 16-bit instructions.

In conclusion, it looks like we could add 32-bit shared memory instructions fairly easily without having to poke around in L3 land, which is good because it significantly reduces the scope :)

Initially I suggest adding them for shared memory only---that way you don't have to deal with them much anywhere above `lab_to_target`. I assume this would be acceptable, since it's mainly for interacting with device registers? Supporting it for local memory is possible but more work.

For 16-bit instructions, we'd have to make it an optional instruction since we don't have it for MIPS or ag32.
