### ISSUE TITLE
Add word64 primitive type

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#106]
Add a word64 primitive type, plus operations over it (operations list forthcoming from @myreen). Note the semantics would ideally re-use a semantic helper function down through all intermediate languages for the word operations.

**Comment by myreen** [comment]
Here are the basic operations that must be supported:

- and `word_and`
- or `word_or`
- xor `word_xor`
- left shift `word_lsl`
- unsigned right shift `word_lsr`
- signed right shift `word_asr`
- add `word_add`
- sub `word_sub`

We also need conversions. Obviously we'll want to convert to/from bytes:

- word-to-byte `(w2w:word64->word8)`
- byte-to-word `(w2w:word8->word64)`

One could have signed `sw2sw` versions of these, but please see comment below.

One can decide whether we should convert between integers or natural numbers. For the implementation, I'm certain that conversions to/from non-negative integers is the simplest option and is sufficient for the translator.

- nat-to-word `\i. if i < 0 then 0w else n2w (Num i)`
- word-to-nat `\w. & (w2n w)`

To make our support for `word64` seem normal, we might have to include conversions for signed word representations as follows. I'm not keen on these because they'll just cause complications. One can of course implement the int-to/from-word conversions using the nat-to/from-word conversions, but with some minor performance penalties.

- int-to-word `i2w` from `integer_wordTheory`
- word-to-int `w2i` from `integer_wordTheory`

**Comment by myreen** [comment]
I would like to add that the basic operations (and, or, ..., sub) listed above should also be available for the byte type (so that the translator can seamlessly support 'a word and map word8 to bytes in CakeML).

**Comment by xrchz** [comment]
`i2w`, `w2i`, `n2w`, and `w2n` are all already supported by the translator (for bytes only of course). Can you please check whether the current semantics is what you would like for them? And if not, I might also want to ask your help in changing it since it's a delicate balance getting everything to line up.

**Comment by myreen** [comment]
By current semantics I guess you mean `W8fromInt` and `W8toInt`. I would prefer to only have unsigned versions. Currently, the semantics uses signed conversions `i2w` and `w2i`. It is in general much easier to deal with `n2w` and `w2n`. The translator can of course be made to translate any of them (`i2w`, `w2i`, `n2w`, `w2n`) whatever semantics we chose for `W8fromInt` and `W8toInt`, and `W64fromInt` and `W64toInt`. 

I guess we want to be consistent with the word-to/from-int conversion functions in SML. I see that the [Poly/ML documentation](http://www.polyml.org/documentation/Reference/Basis.html#Word64) states that `Word64` are unsigned, and its conversion functions `toInt` and `fromInt` are unsigned (and supports `toIntX` and `fromIntX` for signed conversions.) 

I think we should try to be consistent with Poly/ML's `Word64`s so that we can run CakeML code on Poly/ML as much as possible.

**Comment by xrchz** [comment]
@myreen If you want to change the semantics of `W8fromInt` and `W8toInt`, could you make the change and update the translator and compiler proofs? I went back and forth a lot with these initially, and found the current version to play much nicer with the data refinement through the compiler, hence I am initially sceptical of it being an easy change.

With regard to SML and compatibility, I think it does not matter what our primitives are: we should and will expose both signed and unsigned versions and I believe they can be implemented in terms of each other.

**Comment by myreen** [comment]
@xrchz I made the change to the semantics of `W8fromInt` and `W8toInt`. The change was simple: it just required consistently replacing `w2i` with `λw. & (w2n w)`. As a bonus we got rid of the terrible integer-to-integer `W8FromInt` primitive from closLang onwards. With the unsigned-word semantics, the pat-to-clos compiler translates `W8FromInt ...` to `... Mod 256`.

**Comment by xrchz** [comment]
I think this is done. The only thing potentially missing is the 32-bit versions of the word64 ops in data-to-word. But that can be addressed by #27.
