### ISSUE TITLE
Isabelle/HOL and Coq definitions for the source semantics for CakeML

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#125]
One of the motivations (see https://wiki.cakeml.org/Conventions) for using Lem for the definition of the CakeML semantics was to be able to export the source semantics to different tools/logics, e.g. Isabelle/HOL and Coq.

We should produce and maintain Isabelle/HOL and Coq definitions of the source semantics.

**Comment by freekwiedijk** [comment]
Hi Magnus,

>One of the motivations (see
>https://wiki.cakeml.org/Conventions) for using Lem for
>the definition of the CakeML semantics was to be able to
>export the source semantics to different tools/logics,
>e.g. Isabelle/HOL and Coq.
>
>We should produce and maintain Isabelle/HOL and Coq
>definitions of the source semantics.

We had a student, Rodin Aarssen, write his master's thesis
on a Lem version of Robbert's "CH2O" operational semantics
for C, for exactly this reason.  It turned out that the
Coq generated by Lem is rather rudimentary and not really
something a Coq user would accept.  I think.

Two problems were that:

- The distinction between Prop and bool in Coq is not
  present in Lem.  In Coq inductively defined relations
  need to be in Prop, and you can only do a match or an
  if-then-else on a bool.  In the C semantics counterparts
  to both types were needed, but there was just one "bool"
  in Lem.

- The generated Coq is _not_ free of axioms (something that
  is heavily frowned on in the Coq community).  Even worse,
  there is an axiom ("DAEMON") that is a proof of False.
  Of course that axiom can be manually removed if it's not
  used, but it looks weird.

However, it was clear that the Lem in this case maps
straight-forwardly into very simple and clean Coq (the
type theory of Coq is much more expressive than Lem).
It's just that Lem doesn't produce that automatically.

Freek

**Comment by xrchz** [comment]
@larsrh probably has experience relevant to this

**Comment by larsrh** [comment]
The translation to Isabelle is relatively straightforward, but it does require some minor manual changes. At this point I don't know what to do with the exported Isabelle code that's in my private repository; it is very likely thought that it will eventually be in the AFP (in its own entry, potentially).  I am open for suggestions though!

**Comment by larsrh** [comment]
I think this issue can be closed now. There is a (unofficial) version of the source semantics in the AFP: https://devel.isa-afp.org/entries/CakeML.html. There is also tooling support to keep it up-to-date: https://github.com/larsrh/isabelle-cakeml

**Comment by xrchz** [comment]
I agree: if someone wants Coq definitions, open a separate issue.
