### ISSUE TITLE
Combine single moves into parallel moves wordLang

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#130]
The `data_to_word` compiler currently never produces parallel moves, but `wordLang` supports them and `word_to_stack` compiles them well. An inspection of some code Yong Kiam produced with the compiler shows that there are a lot of single Moves that ought to be lumped together.

**Comment by myreen** [comment]
A closer look at the compiler suggests that the right way to fix this is to avoid producing the moves in the first place. I believe the right fix is to attempt to change this line in `bvi-to-data`:

  https://github.com/CakeML/cakeml/blob/master/compiler/backend/bvi_to_dataScript.sml#L47

into:

     else (Skip, [EL v env], n)) /\

Yong Kiam pointed out in a recent email that it would be better still to use a version of `EL` that doesn't  produce side conditions when run through the translator.

**Comment by tanyongkiam** [comment]
As Magnus suggests. combining single moves isn't that important after 5e7fbf8

The remaining moves generated in bvi_to_data arise when one needs to merge the results of the two branches of Ifs and Calls (with handlers). It might be possible to optimize it so that a Move is only needed for one of these branches.

It might still be nice to do a parallel moves pass in wordLang.

**Comment by xrchz** [comment]
Shall we close this now, considering it's not important any more?

**Comment by tanyongkiam** [comment]
I'm re-opening this issue, since a more recent inspection of the generated code indicates that there is indeed room for improvement w.r.t. combining moves into parallel ones.

Here's a snippet (straight line code):
  Move 0 [(193,157)]
  Move 0 [(197,161)]
  Move 0 [(201,197)]
  Inst (Arith (Shift Lsl 201 201 30))
  Move 0 [(205,193)]
  Inst (Arith (Binop Or 205 205 (Reg 201))

A more ambitious version of this would be to move across instructions as well.
The above code could e.g. become:
  Move 0 [(193,157), (197,161), (201,161), (205,157)]
  Inst (Arith (Shift Lsl 201 201 30))
  Inst (Arith (Binop Or 205 205 (Reg 201))

I think combining adjacent Moves will strictly improve performance, but moving across instructions might not, so probably some sort of limit needs to be set on the number of instructions to move across.

**Comment by tanyongkiam** [comment]
Slightly more investigation indicates that many of these extra moves are produced by the three-to-two reg pass.

The move-combination pass should probably go in-between that and register allocation.
