### ISSUE TITLE
Rename arm -> arm6 (or vice versa)

### ISSUE THREAD

**Issue by tanyongkiam** [CakeML/cakeml#139]
Currently, the arm6 related stuff is called 'arm' in a few places (L3-examples, stack_names), but arm6 elsewhere. It would be nice if they were all uniformly called arm6 (or arm).

**Comment by acjf3** [comment]
The underlying ISA model in examples/l3-machine-code/arm covers ARMv4 to ARMv7, so it doesn't make sense to call that "arm6". Under CakeML the model is specialised to ARMv6. This is significant because ASM's Call and JumpReg instructions are implemented with BLX and BX, which aren't available under ARMv4. So it's probably best not to call things "arm" under target, since arm6_ok asserts that the architecture is ARMv6 (and the proofs rely on this).

With a bit of work it should be possible to generalise things such that CakeML supports ARMv4 through to ARMv7. (For ARMv4 asm_ok would be false for Call and two instructions would be needed for JumpReg.) If that were done then it would make sense to rename things to "arm" under CakeML. I can look into doing this if there is sufficient interest?

**Comment by xrchz** [comment]
It would be nice, but I'd say #109 is a much higher priority. (We don't currently have plans to run on ARMv4, but it would be good to have the option and possibly good for marketing.)

**Comment by xrchz** [comment]
@tanyongkiam does Anthony's response clarify the naming scheme currently used? Supposing we don't generalise to support ARMv4-7, does anything need to be done for this issue?

**Comment by tanyongkiam** [comment]
Closed as not fixing.
