### ISSUE TITLE
Replace FFI indexes with FFI names

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#159]
FFI calls currently take a number which indicates which external function is to be called. The numbers are convenient for the compiler, but inconvenient for all other purposes. 

I suggest we replace FFI indexes (num) with FFI names (string). This way one can avoid magic numbers, i.e. have the compiler pick the numbers. Reasoning and modelling FFI behaviour will also be a bit more convenient once we have names instead of numbers.

**Comment by xrchz** [comment]
I think this is not quite finished: `x64_exportLib` still uses names `ffi0`, `ffi1`, etc. and expects the compiler to return the number of FFI calls rather than their names.

**Comment by IlmariReissumies** [comment]
I found this puzzling since I had already updated x64_exportLib. It turns out that there are two verbatim copies of it (compiler/eval/x64/x64_exportLib.sml and compiler/eval/targets/x64_exportLib.sml), and I had only updated one of them. Perhaps @tanyongkiam can see about addressing this code duplication while you're reorganising eval? :)
