### ISSUE TITLE
Include If in every IL

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#172]
`If` is part of almost every intermediate language in the compiler. Curiously it is not part of `conLang`, `decLang`, `exhLang`. In these languages, `If` is represented by pattern matching. Instead of `If (n < 3) t1 t2` one has something along the lines of:

    case (n < 3) of true => t1 | _ => t2

The problem is that the above pattern match causes an unnecessary indiretion. In patLang it becomes:

    let x = (n < 3) in if x = true then t1 else t2

and the compiler writer has made an implicit assumption that the rest of the compiler is smart enough to notice that `x` can be removed.

I believe that the compiler is not currently smart enough to notice this. Furthermore, it's dangerous to rely on the rest of the compiler being smart enough to fix bad code produced higher up in the compiler.

I suggest that `If` is included in every IL, including `conLang`, `decLang`, `exhLang`.

**Comment by xrchz** [comment]
I don't think it is a good idea to make this change without also making the compiler smart enough to detect and optimise the kinds of pattern matches that currently appear in `exhLang` etc. for `If`.

The reason is that we want all code of the form "two branches with nullary constructor" to be optimised, and also all code of the form "if where the test is an equality with a constant boolean" to be optimised. The first one at least should be a relatively easy addition to the `exh_simp` phase. The second one should be easy to add to the "smart if" of `exh_to_pat`. (Of course, eventually we might replace the entire pattern match compiler with something much better, so maybe we want to save the work..)

If we add `If` to more languages, it makes the proofs more cumbersome without addressing the real problem.

**Comment by myreen** [comment]
I think we have differing views on what the optimisations ought to look like. It's the `let` that I'm worried about. Here's how I imagine the necessary optimisations:

    if x = true then ... else ...  ==>   if x then ... else ...

    let x = exp in if x then ... else ...  ==>  if exp then (let x = 0 in ...) else (let x = 0 in ...)  

The second one could only fire in case both `...` do not mention 0. For this compiler phase, one needs to compute the free variables of `...`, which for efficiency reasons must be done in a bottom-up sweep along with the recursion of the compiler phase. I inserted the `0` in the example above so that we don't have to shift indexes. The added `let x = 0 in` is harmless.

Both of these would easily be implemented and proved in BVL. However, it would be nicer if the fixing of the bad code happens as close as possible to the generation of the bad code.

In the future, whenever we know that a compiler phase is going to need some smarts in the later parts of the compiler, then let's make an issue for the smarts so that we don't forget to implement them.

**Comment by xrchz** [comment]
I would call your first optimisation example "if where the test is an equality with a constant boolean". I think it should also be done for `if x = false ...`.

However, I don't understand your second example. What I mean by "two branches with nullary constructor" is the following:
```
case exp of C => exp1 | pat => exp2 ==> if exp = C then exp1 else exp2
```
This way, the `let` never gets introduced.

**Comment by myreen** [comment]
OK. I guess both of these could be implemented as "smart" versions of normal AST constructs: `SmartIf` does the following:

    if x = true then (a) else (b)  ==>   if x then (a) else (b)
    if x = false then (a) else (b)  ==>   if x then (b) else (a)

and the other optimisation could be a `SmartMat`. By the way, it is not clear to me how it would work with the variable pattern for the second optimisation. I guess your variable indexes are a bit off in the generated code. Also what happens if `exp2` uses this variable? (It would be inefficient to have `SmartMat` check for free variables with a `free_vars` function.)

**Comment by myreen** [comment]
I don't understand "I realised it's important that the second pattern is a variable for this". In `exhLang` you know that every pattern match must be exhaustive, so your "two branches with nullary constructor" optimisation should work, I think. 

    case exp of C1 => exp1 | C2 => exp2   ==>   if exp = C1 then exp1 else exp2

Maybe I'm missing something.

**Comment by xrchz** [comment]
You're right: variable patterns make things difficult. But if there are two nullary constructors, that optimisation does work. Note that the phase that makes pattern matches exhaustive never introduces constructor patterns. However, it looks like for the compilation of if, we do end up with explicit `true` and `false` patterns, so it should work.

**Comment by xrchz** [comment]
Discussing with @myreen, it seems there may be problems with optimising `if x = true/false then ...` generally, because of the semantics of equality when `x` is not a boolean. So, probably the right thing to do is to fuse the two optimisations together. Specifically, we should have only one optimisation, of `case exp of C1 => exp1 | C2 => exp2`, which produces an `if` testing just `exp` if the constructors are booleans, or else produces an `exp = C1` test.

**Comment by xrchz** [comment]
Given this optimisation, can we remove `If` from the source language AST (and have it be syntactic sugar)?

**Comment by tanyongkiam** [comment]
All relevant languages have If now.
