### ISSUE TITLE
Why no HOL4 submodule?

### ISSUE THREAD

**Issue by rrnewton** [CakeML/cakeml#19]
From the README:

```
 We develop this using the head of the HOL4 development version in Github
```

But shouldn't the cakeml repo then include HOL4 as a submodule to have a future-proof and reproducible link between a version of cakeml and the version of HOL4 it works with?

**Comment by xrchz** [comment]
That's a good point: I think the reason is none of us is very familiar with submodules, but I'll look into this soon.

**Comment by myreen** [comment]
Would it mean that one needs to build HOL for each directory where some
branch of CakeML is checked out? I'm not familiar with submodules.. --
Magnus

**Comment by xrchz** [comment]
After looking a bit closer at submodules (e.g., http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/ and the things it links to), and considering Magnus's comment (to which I think the answer is yes), I'm less inclined to want to use them.

I think I can answer Ryan as follows:

We don't include HOL as a submodule because we typically share a single working copy of HOL across multiple clones of (different branches of) cakeml while developing. If HOL were a submodule, each HOL would need to be built separately, taking time and breaking environment variables like $HOLDIR. Typically, the same version of HOL works for all the cakeml branches anyway.

To specify and future-proof the link between a version of cakeml and a version of HOL, I think when we make a _release_ of CakeML (e.g. a tagged commit with a version number), we will include the HOL revision (preferably a released version of HOL too) that it works with. For development between releases, I think being sloppy with "always use the latest" is good enough in practice.

I'd be happy to hear if you know good reasons to reconsider.
