### ISSUE TITLE
translator produces datatypes with long-named constructors

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#22]
For example:

```
datatype term = Abs of Kernel.term * Kernel.term
              | Comb of Kernel.term * Kernel.term
              | Const of Kernel.mlstring * Kernel.type
              | Var of Kernel.mlstring * Kernel.type
```

The `Kernel.term` parts probably need to be just `term` instead. For the other occurrences of `Kernel.` it's not as clear what the right thing to do is, but probably removing the module name `Kernel.` is better.

**Comment by tanyongkiam** [comment]
I think there's a problem handling this cleanly in the pretty printer without carrying information about the structure of the program.

One way to handle this is to check whether we are "inside" the module declaration for that type (e.g. Kernel for term) and skip the module name in the printing. However,

Consider:
structure Kernel = struct datatype term = Foo end;

structure Kernel = struct datatype term = Foo of Kernel.term end;

That's a legitimate need to print Kernel.term instead of just term but I don't see an immediate way to tell.

Should the types in a module just be printed without the long names at all then?

**Comment by xrchz** [comment]
Well, we don't allow duplicated module names, but if you used different module names in your example there might still be a need to use a long name since the type from the first module would not be in scope.

I think a bias for short names is better than one for long names, since it's more often going to be correct. But as you note a real solution would give the pretty-printer more information about what is currently in scope. I think it's enough for the pretty-printer to know the current module name, and to not print it (but to print other module names).

**Comment by tanyongkiam** [comment]
Actually, could you give an example of the unpretty-printed term that you are trying to print? I just tried out the following:
val prog =
   ``"structure Foo = struct datatype foo = Foo of foo * foo | Foo2 end;"``:

val t1 =
   |- get_all_asts
     "structure Foo = struct datatype foo = Foo of foo * foo | Foo2 end;" =
   Success
     [Tmod "Foo" NONE
        [Dtype
           [([],"foo",
             [("Foo",
               [Tapp [] (TC_name (Short "foo"));
                Tapp [] (TC_name (Short "foo"))]); ("Foo2",[])])]]]:
   thm

This pretty prints correctly (namely, because the parser does not assign a long name to foo).

**Comment by xrchz** [comment]
The example I'm interested in is the HOL kernel produced in `hol-light/standard/ml_kernel/`. I think the long names probably get added by the translator (so maybe this is more of a translator issue than a pretty-printer issue).

**Comment by xrchz** [comment]
I'm calling this a bug because it means the translator generates datatype definitions inside modules that don't type check.
