### ISSUE TITLE
Int.toString and Int.fromString

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#226]
Requesting addition of an `Int` module to the basis library (this should probably appear in `basis/pure/mlintScript.sml` and `basis/pure/mlintProgScript.sml` on the `basis` branch) with to- and from-string functions at least. Note that these functions exist in HOL already (e.g., `num_from_dec_string`) and some equation based on those functions should probably be translated to obtain this functionality.

**Comment by myreen** [comment]
I recently defined a translator-friendly version of one such function:

https://github.com/CakeML/cakeml/blob/master/compiler/eval/targets/export_x64Script.sml#L42

Note that a good implementation should probably divide the original number by large chunks first, e.g. 100000000, and then do fast small divisions by 10 within the smaller chunks. I suggest 100000000 because it is smaller than the cutoff in `bvl_to_bvi`, i.e. 

https://github.com/CakeML/cakeml/blob/master/compiler/backend/bvl_to_bviScript.sml#L22

**Comment by xrchz** [comment]
@tanyongkiam notes that there is a rudimentary translatable `parse_num` function here https://github.com/CakeML/cakeml/blob/master/compiler/compilerScript.sml#L57

**Comment by xrchz** [comment]
`exportTheory` defines a `num_to_str` which should be replaced by `mlintTheory.toString`.
