### ISSUE TITLE
FileIO.inputLine keeps newlines in the result

### ISSUE THREAD

**Issue by oskarabrahamsson** [CakeML/cakeml#346]
This seems a bit odd; the use case for functions such as `inputLine` and `inputLines` (for me, at least) is when you are _not_ interested in keeping newlines/carriage return/etc in the result.

**Comment by xrchz** [comment]
This is clearly the specified semantics in the SML basis library, at least for `inputLine` (http://sml-family.org/Basis/text-io.html#SIG:TEXT_IO.inputLine:VAL).

It would be great to augment the CakeML basis library with additional (efficient, useful) variants of such functions. I suppose this issue can be closed if either you decide you don't need a non-newline-preserving variant, or someone implements one. Note, new functions should go into the fsio-based I/O module (currently under development on a branch) rather than the current `FileIO` module, since that is going to be deprecated.

**Comment by oskarabrahamsson** [comment]
I'm not opposed to keeping it the way it is if it's clearly specified. I am fine without one for the time being so I'll close it.
