### ISSUE TITLE
Summarise the differences between CakeML and Standard ML

### ISSUE THREAD

**Issue by cartazio** [CakeML/cakeml#433]

**Comment by AndreasLoow** [comment]
Things not covered would probably also be useful to include. And possibly also a short description of why things that differ differ.

**Comment by xrchz** [comment]
Here are some relevant chat logs as a starting point:

CakeML differs from SML on a few things and doesn't include some things. The complete formal semantics for CakeML is in the `semantics` directory of the repository.

Off the top of my head, differences:
- right-to-left evaluation order
- no equality types / semantics of equality
- preference for curried rather than tupled style (shows up in basis library discrepancies)

and missing:
- functors
- records
- open
- local declarations
- let polymorphism
- lots of the basis library
