### ISSUE TITLE
check arity before uniform evaluation in semantics of primitives

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#46]
As per https://lists.cakeml.org/private/dev/2015-June/000983.html, the existing `if` expressions should be replaced using a total version of `EL`.

**Comment by xrchz** [comment]
I don't think the proposed solution works. Consider the length check for compilation of `(App (El n) es)`, which currently checks that `LENGTH es = 1`. If the length of `es` is not `1`, then there will be a type error in the semantics when it gets to `do_app`, but it first evaluates all of `es` in reverse order and propagates any error raised by them. If the compiled code only looks at `EL 0 es`, it won't necessarily raise the correct error. Hence the current compiler produces an expression that includes all of `es` in the correct order in case the length check fails.

I think if you want to push the length check into some `EL`-with-default, the semantics will need to change to do the length check before evaluating the argument expressions.

**Comment by SOwens** [comment]
> On 2015/07/01, at 21:21, Ramana Kumar <notifications@github.com> wrote:
> 
> I don't think the proposed solution works. Consider the length check for compilation of (App (El n) es), which currently checks that LENGTH es = 1. If the length of es is not 1, then there will be a type error in the semantics when it gets to do_app, but it first evaluates all of es in reverse order and propagates any error raised by them. If the compiled code only looks at EL 0 es, it won't necessarily raise the correct error. Hence the current compiler produces an expression that includes all of es in the correct order in case the length check fails.
> 
> I think if you want to push the length check into some EL-with-default, the semantics will need to change to do the length check before evaluating the argument expressions.

This is the right thing to do. The general principle is that the semantics should type error as much as possible. This allows the compiler more flexibility. It is also similar to the recent change to the FFI that allowed evaluation to proceed beyond an FFI error in order to get to a type error.

The problem is that it’s not trivial to implement. The semantics uses a uniform evaluation strategy for the arguments to primitives, which evaluates the arguments before checking the primitive. I don’t think we want to change to having separate primitive application forms for 1, 2, and 3 (and possibly more) arguments. Another approach would be to have a mapping from primitives to arities, and check the length before doing the uniform evaluation. I don’t know if it’s worth the hassle.

-Scott

**Comment by xrchz** [comment]
I think checking with a map from primitives to arities is a good idea. Maybe that map could be defined in terms of `do_app` (e.g. `@n. !l. ?x. do_app op l = SOME x ==> LENGTH l = n`) rather than manually.

**Comment by xrchz** [comment]
I think this also affects `compile_op` in `bvl_to_bvi`. I see this otherwise strange case-split there on a list that should always be empty:
```
    | Const i => (case c1 of [] => compile_int i
                  | _ => Let [Op (Const 0) c1] (compile_int i))
```
