### ISSUE TITLE
Incredibly large toX script files in bootstrap/translation

### ISSUE THREAD

**Issue by mn200** [CakeML/cakeml#531]
Could we not break some of these up so that failing translations need not throw away large quantities of successful translation that preceded the error in super-large files?  Debugging errors in the bootstrap is otherwise extremely dispiriting.

If we had a long chain of smaller files, more progress would get saved.  Of course, the need to linearise is not ideal, but linear chains of massive files is particularly grim.

**Comment by myreen** [comment]
Sounds like a good idea. Which files are particularly bad?

**Comment by oskarabrahamsson** [comment]
I agree that this is useful. I think the overhead from loading/storing theories a few more times is definitely worth it. It would be nice have one toXScript for each pass, e.g. source_to_flat, flat_to_pat, pat_to_clos, etc. 

My personal experience is that all the 'interesting' stuff happens somewhere deep inside to_dataProgScript (clos, bvl or bvi), and running that interactively to the end just to fix a tiny thing takes quite some time.

**Comment by oskarabrahamsson** [comment]
@lorenzleutgeb translation is linear so it has to be stuck in somewhere. If I recall correctly, lexerProg previously appeared before to_dataProg, but was moved down so that you would not have to build it just to go in and apply fixes to to_dataProg (which is much more likely to need adjustments when things change in the compiler).

**Comment by xrchz** [comment]
Is this done now following #584?

**Comment by oskarabrahamsson** [comment]
This was done in #584.
