### ISSUE TITLE
mergesortN fails to translate

### ISSUE THREAD

**Issue by myreen** [CakeML/cakeml#63]
Konrad reported that mergesortTheory.mergesortN_def doesn't translate.

**Comment by xrchz** [comment]
I think this alternative version goes through the translator:
```
val mergesortN_alt_def = tDefine "mergesortN_alt" `
(mergesortN_alt R n l =
 if n = 0 then []
 else if n = 1 then case l of [] => [] | h::nl => [h]
 else if n = 2 then case l of [] => [] | [h] => [h] | h1::h2::nl => sort2 R h1 h2
 else if n = 3 then case l of [] => [] | [h] => [h] | [h1;h2] => sort2 R h1 h2 | h1::h2::h3::nl => sort3 R h1 h2 h3
 else let len1 = n DIV 2 in merge R (mergesortN_alt R len1 l) (mergesortN_alt R (n - len1) (DROP len1 l)))`
(WF_REL_TAC`measure (FST o SND)`
 \\ simp[arithmeticTheory.X_LT_DIV]);

val mergesortN_alt_intro = Q.store_thm("mergesortN_alt_intro",
  `mergesortN = mergesortN_alt`,
  simp[FUN_EQ_THM]
  \\ ho_match_mp_tac(theorem"mergesortN_alt_ind") \\ rw[]
  \\ rw[Once mergesortN_alt_def]
  \\ rw[Once mergesortTheory.mergesortN_def,arithmeticTheory.DIV2_def]);

val _ = augment_srw_ss[rewrites[DECIDE``x + 1n = 2 ⇔ x = 1``]]
val res = translate mergesortN_alt_def
```
Is it really a problem that the original definition does not? It's quite a hairy definition.

**Comment by tanyongkiam** [comment]
Closing, because mergesortN_def translates fine on the latest version of the translator now:

val res = translate sort2_def
val res = translate sort3_def
val res = translate DIV2_def
val res = translate merge_def
val res = translate DROP_def
val res = translate mergesortN_def

Output:
Adding type :α list
metis: r[+0+17]+0+0+0+0+0+0+0+0+0+0+0+0+2+2+1+0+0+2+2+1#
r[+0+17]+0+0+0+0+0+0+0+0+0+0+0+0+2+2+1#
r[+0+17]+0+0+0+0+0+0+0+0+0+0+0+0+2+2+0+0+1+0+2+1+0+1+1#
r[+0+17]+0+0+0+0+0+0+0+0+0+0+0+0+2+2+0+0+1#
metis: r[+0+22]+0+0+0+0+0+0+0+0+0+0+0+0+0+0+0+0+1+0+0+2+2+0+0+0+0+5+3+1#
r[+0+22]+0+0+0+0+0+0+0+0+0+0+0+0+0+0+0+0+1+0+0+2+2+0+0+0+0+5+3+1+0+0+0+2#
Case translation: 2 1 done.
Translating sort2
Translating sort3
Translating div2
Translating merge
Translating drop
Translating mergesortn
metis: r[+0+19]+0+0+0+0+0+0+0+0+0+0+0+0+0+0+0+0+0+0+0!
val res =
   |- ((a --> a --> BOOL) --> NUM --> LIST_TYPE a --> LIST_TYPE a)
     mergesortN mergesortn_v:
   thm
