### ISSUE TITLE
Extend translator to support floating-point operations

### ISSUE THREAD

**Issue by HeikoBecker** [CakeML/cakeml#636]

**Comment by HeikoBecker** [comment]
What is the ideal way of implementing this?
Looking at https://github.com/CakeML/cakeml/blob/master/translator/ml_translatorScript.sml#L73 and https://github.com/CakeML/cakeml/blob/master/translator/ml_translatorScript.sml#L861
a `DOUBLE` value should be added and some evaluation theorems about all supported arithmetic operations.

If a `DOUBLE` type were to be added to the translator how should this then be handled in `hol2deep`?
https://github.com/CakeML/cakeml/blob/master/translator/ml_translatorLib.sml#L3139 for example relies on HOL4's type inference and HOL4 double's are just type abbreviations for `word64`.

**Comment by myreen** [comment]
There shouldn't be a `DOUBLE` value. Instead the floating point operations should use the normal `WORD` refinement invariant that is already there. You should use `WORD` with the type fixed to `word64`, because the floating point operations are only available for that word size. The `WORD` refinement type allows for any word size up to and including 64.

The following needs to be done:
 - prove an `Eval` theorem for each primitive operation (see how the operations for `INT` are done)
 - include the new `Eval` theorems in the lists for monop and binop operations in `ml_translatorLib` (and introduce a similar thing for operations that take 3 arguments, 'triop"?)
 - add a few simple tests in `ml_translator_testScript.sml`

**Comment by HeikoBecker** [comment]
I have started working on this on the branch `fp_translation`. So far things seem to work and I will test it further once the pull request for FMA's ( #495) is resolved.
