### ISSUE TITLE
Grammar doesn't accept structures as declarations

### ISSUE THREAD

**Issue by oskarabrahamsson** [CakeML/cakeml#859]
Meaning that this is impossible:
```
local
  structure S = struct end
in end
```
and this, too:
```
structure S = struct
  structure T = struct end
end
```

* Grammar: https://github.com/CakeML/cakeml/blob/master/semantics/gramScript.sml#L219-L224
* PEG, 1: https://github.com/CakeML/cakeml/blob/master/compiler/parsing/cmlPEGScript.sml#L445-L455
* PEG, 2: https://github.com/CakeML/cakeml/blob/master/compiler/parsing/cmlPEGScript.sml#L486-L491

**Comment by mn200** [comment]
I don't expect the grammar should be hard to fix here.  You don't want structures as what the grammar calls  `Decl`s (because those are the things that can appear underneath `let`), but I do think you want to be able to have structures inside `local` and `structure`.   

From scanning `astScript.sml` and `evaluateScript.sml` it looks as if the semantics would cope with both of these (my out-of-date? memory told me these weren't supported before), so I'll definitely put this on the to-do list.  Note that SML allows `local`, `datatype` and `exception` declarations inside `let` expressions, but this still seems to be unsupported by the CakeML semantics so we'll still be a little behind.

**Comment by mn200** [comment]
Note to self: `Decl`s are not those things that can occur under `let`s; those are the `LetDec`s

**Comment by oskarabrahamsson** [comment]
Closing this, since #862 is now merged.
