### ISSUE TITLE
add Bool.not to the initial program, and <> to the parser

### ISSUE THREAD

**Issue by xrchz** [CakeML/cakeml#92]
See https://lists.cakeml.org/private/dev/2015-November/001345.html

**Comment by xrchz** [comment]
@mn200 could you update the parser?

**Comment by mn200** [comment]
It looks from your commit as if you have just defined `not`, so that the translation of `x <> y` should be `not (x = y)`. I guess the translation of `op<>` should be `(fn x => fn y => not (x = y))`?  

If `not` *is* just a top-level identifier, you can get strange effects if the user redefines `not` locally:

    let fun not x = ~x
    in
         fn x => fn y => x <> y
    end

will fail to type-check.

**Comment by xrchz** [comment]
I made `not` a top-level identifier only because that seems to be the way other top-level identifiers are declared in the current initial program. However, a better way might be to declare it inside a `Bool` structure (so the parser can target `Bool.not`, which cannot be redefined), and separately also expose a top-level binding. @SOwens what do you think of this, also for the other top-level identifiers in the initial program? I'm not sure how this will interact with #99.

**Comment by mn200** [comment]
If you're going to provide `not`, can you also just provide `<>`?  The parser already handles that and translates it to `Short "<>"`.

**Comment by xrchz** [comment]
@mn200 I added `<>`. Does that mean this is closed?

**Comment by mn200** [comment]
I think so.  Is there a test-case we could add demonstrating this?

**Comment by xrchz** [comment]
Not really, but it'll be obvious when we have something running.
